[package]
name = "blrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
intel = []

[dependencies]
clap = "3.2.16"
